load 'common.rb'
def p45
  n = 143
  while true
    n += 1
    hex = 2*n**2 - n
    return hex if pentagonal?(hex) && triangular?(hex)
  end
end
def pentagonal?(x)
    ((Math.sqrt(24*x + 1) + 1)/6)%1 == 0
end
def hexagonal?(x)
    ((Math.sqrt(8*x + 1) + 1)/4)%1 == 0
end
def triangular?(x)
    ((Math.sqrt(8*x + 1) - 1)/2)%1 == 0
end


# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle
#  
# Tn=n(n+1)/2
#  
# 1, 3, 6, 10, 15, ...
# Pentagonal
#  
# Pn=n(3n1)/2
#  
# 1, 5, 12, 22, 35, ...
# Hexagonal
#  
# Hn=n(2n1)
#  
# 1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.
